[build]
  publish = "site"

[[redirects]]
  from = "/2006/*"
  to = "/gone.html"
  status = 410

[[redirects]]
  from = "/2007/*"
  to = "/gone.html"
  status = 410

[[redirects]]
  from = "/2008/*"
  to = "/gone.html"
  status = 410

[[redirects]]
  from = "/2009/*"
  to = "/gone.html"
  status = 410

[[redirects]]
  from = "/2010/*"
  to = "/gone.html"
  status = 410

[[redirects]]
  from = "/2011/*"
  to = "/gone.html"
  status = 410

[[redirects]]
  from = "/2012/*"
  to = "/gone.html"
  status = 410

[[redirects]]
  from = "/feeds/*"
  to = "/gone.html"
  status = 410

[[redirects]]
  from = "/search*"
  to = "/"
  status = 302
